title: Page
icon: 📄

columns:
  main:
    width: 2/3
    sections:
      content:
        type: fields
        fields:
          body:
            label: Content
            type: blocks
            fieldsets:
              text:
                label: Text
                type: group
                fieldsets:
                  - heading
                  - text
                  - list
                  - quote
                  - markdown
              media:
                label: Media
                type: group
                fieldsets:
                  - image
                  - gallery
                  - video
              code:
                label: Code
                type: group
                fieldsets:
                  - code

  sidebar:
    width: 1/3
    sections:
      meta:
        type: fields
        fields:
          updated:
            label: Last Updated
            type: date
            help: Optional date shown on page
      files:
        type: fields
        fields:
          cover:
            label: Cover Image
            type: files
            max: 1
            uploads:
              template: image
      pages:
        type: pages
        template: default
      attachments:
        type: files
        label: Attachments
