title: Site

tabs:
  profile:
    label: Profile
    icon: user
    sections:
      author:
        type: fields
        fields:
          author_name:
            label: Name
            type: text
            required: true
          author_tagline:
            label: Tagline
            type: text
            help: Short tagline, e.g. "Curious. Creative. Coder."
          author_bio:
            label: Bio
            type: textarea
            help: Short bio for homepage header
          author_image:
            label: Profile Photo
            type: files
            max: 1
            uploads:
              template: image
          header_image:
            label: Header Background
            type: files
            max: 1
            help: Gradient/blur background for home page
            uploads:
              template: image

  social:
    label: Social
    icon: heart
    sections:
      links:
        type: fields
        fields:
          social_links:
            label: Social Links
            type: structure
            fields:
              platform:
                label: Platform
                type: select
                options:
                  bluesky: Bluesky
                  fediverse: Fediverse
                  github: GitHub
                  email: Email
                  rss: RSS
              url:
                label: URL
                type: text
                help: "Accepts URLs and mailto: links"
              icon:
                label: Icon
                type: select
                options:
                  bluesky: Bluesky
                  fediverse: Fediverse
                  mail: Mail
                  rss: RSS
                  subscribe: Subscribe
      bluesky:
        type: fields
        fields:
          bluesky_import_tags:
            label: Bluesky Import Hashtags
            type: tags
            help: "Posts with any of these hashtags will be imported. Enter without # (e.g., 'buildinpublic')."

  subscribe:
    label: Subscribe
    icon: rss
    sections:
      newsletter:
        type: fields
        fields:
          newsletter_url:
            label: Newsletter URL
            type: url
            help: Buttondown subscription URL
          rss_feeds:
            label: RSS Feeds
            type: structure
            fields:
              name:
                label: Feed Name
                type: text
              url:
                label: Feed URL
                type: url
              description:
                label: Description
                type: text

  footer:
    label: Footer
    icon: quote
    sections:
      quotes:
        type: fields
        fields:
          quote_left:
            label: Left Quote
            type: text
            default: less, but better.
          quote_right:
            label: Right Quote
            type: text
            default: trust the process.

  content:
    label: Content
    icon: text
    columns:
      left:
        width: 1/2
        sections:
          posts:
            type: pages
            label: Posts
            parent: site.find("posts")
            template: post
            status: all
            info: "{{ page.date.toDate('M d, Y') }}"
            sortBy: date desc
          notes:
            type: pages
            label: Notes
            parent: site.find("notes")
            template: note
            status: all
            info: "{{ page.date.toDate('M d, Y H:i') }}"
            sortBy: date desc
      right:
        width: 1/2
        sections:
          photos:
            type: pages
            label: Photos
            parent: site.find("photos")
            template: photo
            status: all
            image: true
            info: "{{ page.date.toDate('M d, Y') }}"
            sortBy: date desc
          races:
            type: pages
            label: Races
            parent: site.find("races")
            template: race
            status: all
            info: "{{ page.distance }}km in {{ page.time }}"
            sortBy: date desc

  analytics:
    label: Analytics
    icon: chart
    sections:
      plausible:
        type: fields
        fields:
          plausible_domain:
            label: Plausible Domain
            type: text
            placeholder: dominikhofer.me
            help: Your site's domain tracked in Plausible
          plausible_script:
            label: Plausible Script URL
            type: url
            placeholder: https://analytics.linea.studio/js/script.outbound-links.js
            help: URL to your Plausible tracking script

  pages:
    label: Pages
    icon: page
    sections:
      pages:
        type: pages
        parent: site
        templates:
          - default
          - home
